StoreFront.UI.MVC/Controllers/PricePersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFront.DATA.EF;

namespace StoreFront.UI.MVC.Controllers
{
    public class PricePersController : Controller
    {
        private StoreFrontEntities db = new StoreFrontEntities();

        // GET: PricePers
        public ActionResult Index()
        {
            return View(db.PricePers.ToList());
        }

        // GET: PricePers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PricePer pricePer = db.PricePers.Find(id);
            if (pricePer == null)
            {
                return HttpNotFound();
            }
            return View(pricePer);
        }

        // GET: PricePers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PricePers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PriceID,Description")] PricePer pricePer)
        {
            if (ModelState.IsValid)
            {
                db.PricePers.Add(pricePer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pricePer);
        }

        // GET: PricePers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PricePer pricePer = db.PricePers.Find(id);
            if (pricePer == null)
            {
                return HttpNotFound();
            }
            return View(pricePer);
        }

        // POST: PricePers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PriceID,Description")] PricePer pricePer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pricePer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pricePer);
        }

        // GET: PricePers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PricePer pricePer = db.PricePers.Find(id);
            if (pricePer == null)
            {
                return HttpNotFound();
            }
            return View(pricePer);
        }

        // POST: PricePers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PricePer pricePer = db.PricePers.Find(id);
            db.PricePers.Remove(pricePer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StoreFront.UI.MVC/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFront.DATA.EF;
using StoreFront.UI.MVC.Utilities; // Added for Image Utility
using StoreFront.UI.MVC.Models; // Added for Cart

namespace StoreFront.UI.MVC.Controllers
{
    public class ProductsController : Controller
    {
        private StoreFrontEntities db = new StoreFrontEntities();

        // GET: Products
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Category).Include(p => p.PricePer).Include(p => p.Status);
            return View(products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName");
            ViewBag.PriceID = new SelectList(db.PricePers, "PriceID", "Description");
            ViewBag.StatusID = new SelectList(db.Status, "StatusID", "Description");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,ProductName,CategoryID,Image,ProductDesc,UnitPrice,PriceID,StatusID")] Product product, HttpPostedFileBase logo)
        {
            if (ModelState.IsValid)
            {

                #region File Upload

                // Use default image in none provided
                string file = "Unavailable.jpg";

                if (logo != null)
                {
                    // Reassign variable that held default image to name of uploaded file
                    file = logo.FileName;
                    // Get ext part of file name
                    string ext = file.Substring(file.LastIndexOf('.'));
                    // Approved filed extensions
                    string[] goodExts = { ".jpeg", ".jpg", ".png", ".gif" };

                    // Check uploaded file ext against goodExts & check file size <= 4mb (ASP.NET default max)
                    if (goodExts.Contains(ext.ToLower()) && logo.ContentLength <= 4194304)
                    {
                        // Create new file name using guid and add file ext
                        file = Guid.NewGuid() + ext;

                        #region Resize Image

                        // Define file path where images will be saved
                        string savePath = Server.MapPath("~/Content/img/product/");
                        // Convert the HttpPostFileBase to an object of type Image so Image Utility can manipulate dimenstions
                        Image convertedImage = Image.FromStream(logo.InputStream);
                        // Define max size for full size & thumbnail pic in px
                        int maxImageSize = 500;
                        int maxThumbSize = 100;
                        // Pass data to ResizeImage() on the image utility
                        ImageUtility.ResizeImage(savePath, file, convertedImage, maxImageSize, maxThumbSize);
                        #endregion

                    }

                    // Update name of image file that will be saved in DB
                    product.Image = file;

                }

                #endregion

                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", product.CategoryID);
            ViewBag.PriceID = new SelectList(db.PricePers, "PriceID", "Description", product.PriceID);
            ViewBag.StatusID = new SelectList(db.Status, "StatusID", "Description", product.StatusID);
            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", product.CategoryID);
            ViewBag.PriceID = new SelectList(db.PricePers, "PriceID", "Description", product.PriceID);
            ViewBag.StatusID = new SelectList(db.Status, "StatusID", "Description", product.StatusID);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,ProductName,CategoryID,Image,ProductDesc,UnitPrice,PriceID,StatusID")] Product product, HttpPostedFileBase logo)
        {
            if (ModelState.IsValid)
            {
                #region File Upload

                string file = product.Image;

                if (logo != null)
                {



                    file = logo.FileName;
                    string ext = file.Substring(file.LastIndexOf('.'));
                    string[] goodExts = { ".jpeg", ".jpg", ".png", ".gif" };

                    if (goodExts.Contains(ext.ToLower()) && logo.ContentLength <= 4194304)
                    {
                        file = Guid.NewGuid() + ext;

                        #region Resize Image

                        string savePath = Server.MapPath("~/Content/img/product/");
                        Image convertedImage = Image.FromStream(logo.InputStream);
                        int maxImageSize = 500;
                        int maxThumbSize = 100;
                        ImageUtility.ResizeImage(savePath, file, convertedImage, maxImageSize, maxThumbSize);

                        #endregion

                        if (product.Image != null && product.Image != "Unavailable.png")
                        {
                            string path = Server.MapPath("~/Content/img/product/");
                            ImageUtility.Delete(path, product.Image);
                        }

                        product.Image = file;

                    }

                    #endregion

                    db.Entry(product).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", product.CategoryID);
            ViewBag.PriceID = new SelectList(db.PricePers, "PriceID", "Description", product.PriceID);
            ViewBag.StatusID = new SelectList(db.Status, "StatusID", "Description", product.StatusID);
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);

            // Delete the image file
            string path = Server.MapPath("~/Content/img/product/");
            ImageUtility.Delete(path, product.Image);

            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        #region AddToCart()

        [HttpPost]
        public ActionResult AddToCart(int qty, int productID)
        {
            // Create an empty version of the LOCAL ShoppingCart (dictionary collection)
            Dictionary<int, CartItemViewModel> shoppingCart = null;

            // Check the cart in the session (GLOBAL) - if it has anything in it, assign its value to local dictionary
            if (Session["cart"] != null)
            {
                // Pull global version to our local version
                shoppingCart = (Dictionary<int, CartItemViewModel>)Session["cart"];
            }
            else
            {
                // Create empty instance of LOCAL dictionary
                shoppingCart = new Dictionary<int, CartItemViewModel>();
            }

            // Get product object being added - firstOrDefault() allows for null return
            Product product = db.Products.Where(p => p.ProductID == productID).FirstOrDefault();

            // If product is null, redirect to index view
            if (product == null)
            {
                return RedirectToAction("Index");
            }
            else
            {
                // Create shoppingCartViewModel

StoreFront.UI.MVC/Controllers/StatusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFront.DATA.EF;

namespace StoreFront.UI.MVC.Controllers
{
    public class StatusController : Controller
    {
        private StoreFrontEntities db = new StoreFrontEntities();

        // GET: Status
        public ActionResult Index()
        {
            return View(db.Status.ToList());
        }

        // GET: Status/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Status status = db.Status.Find(id);
            if (status == null)
            {
                return HttpNotFound();
            }
            return View(status);
        }

        // GET: Status/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Status/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StatusID,Description")] Status status)
        {
            if (ModelState.IsValid)
            {
                db.Status.Add(status);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(status);
        }

        // GET: Status/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Status status = db.Status.Find(id);
            if (status == null)
            {
                return HttpNotFound();
            }
            return View(status);
        }

        // POST: Status/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StatusID,Description")] Status status)
        {
            if (ModelState.IsValid)
            {
                db.Entry(status).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(status);
        }

        // GET: Status/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Status status = db.Status.Find(id);
            if (status == null)
            {
                return HttpNotFound();
            }
            return View(status);
        }

        // POST: Status/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Status status = db.Status.Find(id);
            db.Status.Remove(status);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StoreFront.UI.MVC/Views/Shared/_BreadcrumbPartial.cshtml
<section class="breadcrumb-section set-bg" data-setbg="/../../Content/img/breadcrumb.jpg">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>@ViewBag.Title</h2>
                    <div class="breadcrumb__option">
                        @*<a href="./index.html">Home</a>
                        <span>Shop</span>*@
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<br />
<!-- Breadcrumb Section End -->

StoreFront.UI.MVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity;
<!DOCTYPE html>
<html lang="zxx">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Juni's Grocery</title>
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">
    <!-- Css Styles -->
    @*<link rel="stylesheet" href="~/Content/css/bootstrap.min.css" type="text/css">
        <link rel="stylesheet" href="~/Content/css/font-awesome.min.css" type="text/css">
        <link rel="stylesheet" href="~/Content/css/elegant-icons.css" type="text/css">
        <link rel="stylesheet" href="~/Content/css/nice-select.css" type="text/css">
        <link rel="stylesheet" href="~/Content/css/jquery-ui.min.css" type="text/css">
        <link rel="stylesheet" href="~/Content/css/owl.carousel.min.css" type="text/css">
        <link rel="stylesheet" href="~/Content/css/slicknav.min.css" type="text/css">
        <link rel="stylesheet" href="~/Content/css/style.css" type="text/css">*@

    <link rel="stylesheet" href="//cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" />
    @* Added for datatables.*@


    @Styles.Render("~/Content/css")

</head>
<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>
    <!-- Humberger Begin -->
    <div class="humberger__menu__overlay"></div>
    <div class="humberger__menu__wrapper">
        <div class="humberger__menu__logo">
            <a href="#"><img src="~/Content/img/logo.png" alt=""></a>
        </div>
        <div class="humberger__menu__cart">
            <ul>
                <li><a href="#"><i class="fa fa-heart"></i> <span>1</span></a></li>
                <li><a href="#"><i class="fa fa-shopping-bag"></i> <span>3</span></a></li>
            </ul>
            @*<div class="header__cart__price">item: <span>$150.00</span></div>*@
        </div>
        <div class="humberger__menu__widget">

            <div class="header__top__right__auth">
                <a href="@Url.Action("Login", "Account")"><i class="fa fa-user"></i> Login</a>
            </div>
        </div>
        <nav class="humberger__menu__nav mobile-menu">
            <ul>
                <li class="active"><a href="@Url.Action("Index", "Home")">Home</a></li>
                <li><a href="./shop-grid.html">Shop</a></li>
                <li>
                    <a href="#">Pages</a>
                    <ul class="header__menu__dropdown">
                        <li><a href="./shop-details.html">Shop Details</a></li>
                        <li><a href="./shoping-cart.html">Shoping Cart</a></li>
                        <li><a href="./checkout.html">Check Out</a></li>
                        <li><a href="./blog-details.html">Blog Details</a></li>
                    </ul>
                </li>
                <li><a href="./blog.html">Blog</a></li>
                <li><a href="@Url.Action("Contact", "Home")">Contact</a></li>
            </ul>
        </nav>
        <div id="mobile-menu-wrap"></div>
        <div class="header__top__right__social">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-pinterest-p"></i></a>
        </div>
        <div class="humberger__menu__contact">
            <ul>
                @*<li><i class="fa fa-envelope"></i> hello@colorlib.com</li>*@
                @if (User.IsInRole("Customer") || User.IsInRole("Admin"))
                {
                    @Html.ActionLink("Hello " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                }
            </ul>
        </div>
    </div>
    <!-- Humberger End -->
    <!-- Header Section Begin -->
    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <div class="header__top__left">
                            <ul>
                                @*<li><i class="fa fa-envelope"></i> hello@colorlib.com</li>*@
                                @if (User.IsInRole("Customer") || User.IsInRole("Admin"))
                                {
                                    @Html.ActionLink("Hello " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                                }
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <div class="header__top__right">
                            <div class="header__top__right__social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                                <a href="#"><i class="fa fa-pinterest-p"></i></a>
                            </div>

                            <div class="header__top__right__auth">
                                @Html.Partial("_LoginPartial")
                                @*<a href="@Url.Action("Login", "Account")"><i class="fa fa-user"></i> Login</a>*@
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="header__logo">
                        <a href="./index.html"><img src="~/Content/img/logo.png" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <nav class="header__menu">
                        <ul>
                            <li class="active"><a href="@Url.Action("Index", "Home")">Home</a></li>
                            <li><a href="./shop-grid.html">Shop</a></li>
                            @*<li>
            <a href="#">Pages</a>
            <ul class="header__menu__dropdown">
                <li><a href="./shop-details.html">Shop Details</a></li>
                <li><a href="./shoping-cart.html">Shoping Cart</a></li>
                <li><a href="./checkout.html">Check Out</a></li>
                <li><a href="./blog-details.html">Blog Details</a></li>
            </ul>
        </li>
        <li><a href="./blog.html">Blog</a></li>*@
                            <li><a href="@Url.Action("Contact", "Home")">Contact</a></li>
                            @if (User.IsInRole("Admin"))
                            {
                                <li><a href="#">Admin</a>
                                    <ul class="header__menu__dropdown">
                                        <li><a href="@Url.Action("Index", "Categories")" />Categories</li>
                                        <li><a href="@Url.Action("Index", "Departments")" />Departments</li>
                                        <li><a href="@Url.Action("Index", "Employees")" />Employees</li>
                                        <li><a href="@Url.Action("Index", "PricePers")" />Price Per</li>
                                        <li><a href="@Url.Action("Index", "Products")" />Products</li>
                                        <li><a href="@Url.Action("Index", "Status")" />Status</li>
                                    </ul>
                                </li>
                            }
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-3">
                    <div class="header__cart">
                        <ul>
                            <li><a href="#"><i class="fa fa-heart"></i> <span>1</span></a></li>
                            <li><a href="#"><i class="fa fa-shopping-bag"></i> <span>3</span></a></li>
                        </ul>
                        @*<div class="header__cart__price">item: <span>$150.00</span></div>*@
                    </div>
                </div>
            </div>
            <div class="humberger__open">
                <i class="fa fa-bars"></i>
            </div>
        </div>
    </header>
    <!-- Header Section End -->
    @RenderBody()
    <!-- Footer Section Begin -->
    <footer class="footer spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer__about">
                        <div class="footer__about__logo">
                            <a href="./index.html"><img src="~/Content/img/logo.png" alt=""></a>
                        </div>
                        <ul>
                            <li>Address: 60-49 Road 11378 New York</li>
                            <li>Phone: +65 11.188.888</li>
                            <li>Email: hello@colorlib.com</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6 offset-lg-1">
                    <div class="footer__widget">
                        <h6>Useful Links</h6>
                        <ul>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">About Our Shop</a></li>
                            <li><a href="#">Secure Shopping</a></li>
                            <li><a href="#">Delivery infomation</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">Our Sitemap</a></li>
                        </ul>
                        <ul>
                            <li><a href="#">Who We Are</a></li>
                            <li><a href="#">Our Services</a></li>
                            <li><a href="#">Projects</a></li>
                            <li><a href="#">Contact</a></li>
                            <li><a href="#">Innovation</a></li>
                            <li><a href="#">Testimonials</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12">
                    <div class="footer__widget">
                        <h6>Join Our Newsletter Now</h6>
                        <p>Get E-mail updates about our latest shop and special offers.</p>
                        <form action="#">
                            <input type="text" placeholder="Enter your mail">
                            <button type="submit" class="site-btn">Subscribe</button>
                        </form>
                        <div class="footer__widget__social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer__copyright">
                        <div class="footer__copyright__text">
                            <p>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                Copyright &copy;
                                <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            </p>
                        </div>
                        <div class="footer__copyright__payment"><img src="~/Content/img/payment-item.png" alt=""></div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->
    <!-- Js Plugins -->
    @*<script src="~/Scripts/jquery-3.3.1.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
        <script src="~/Scripts/jquery.nice-select.min.js"></script>
        <script src="~/Scripts/jquery-ui.min.js"></script>
        <script src="~/Scripts/jquery.slicknav.js"></script>
        <script src="~/Scripts/mixitup.min.js"></script>
        <script src="~/Scripts/owl.carousel.min.js"></script>
        <script src="~/Scripts/main.js"></script>*@


    @Scripts.Render("~/bundles/js")
    <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>